require "config.options"
require "config.mappings"

M = {}

M.parsers = {
	"c",
	"go",
	"cpp",
	"css",
	"lua",
	"zig",
	"bash",
	"glsl",
	"fish",
	"html",
	"rust",
	"scss",
	"python",
	"javascript",
}

M.kind_icons = {
	Enum = "",
	File = "",
	Misc = "",
	Text = "󰉿",
	Unit = "",
	Class = "󰠲",
	Color = "",
	Event = "",
	Field = "",
	Value = "󰎠",
	Folder = "",
	Method = "󰡱",
	Module = "",
	Struct = "󰅩",
	Keyword = "",
	Snippet = "",
	Constant = "φ",
	Function = "󰡱",
	Operator = "󰆕",
	Property = "󰯠",
	Variable = "δ",
	Interface = "",
	Reference = "",
	EnumMember = "",
	Constructor = "",
	TypeParameter = "",
}

M.mode_map = {
	["n"] = { "Normal", "blue" },
	["niI"] = { "Normal", "blue" },
	["niR"] = { "Normal", "blue" },
	["niV"] = { "Normal", "blue" },
	["nt"] = { "Normal", "blue" },
	["ntT"] = { "Normal", "blue" },
	["no"] = { "O-Pending", "teal" },
	["nov"] = { "O-Pending", "teal" },
	["noV"] = { "O-Pending", "teal" },
	["no\22"] = { "O-Pending", "teal" },
	["v"] = { "Visual", "maroon" },
	["vs"] = { "Visual", "maroon" },
	["V"] = { "V-Line", "maroon" },
	["Vs"] = { "V-Line", "maroon" },
	["\22"] = { "V-Block", "maroon" },
	["\22s"] = { "V-Block", "maroon" },
	["s"] = { "Select", "mauve" },
	["S"] = { "S-Line", "mauve" },
	["\19"] = { "S-Block", "mauve" },
	["i"] = { "Insert", "green" },
	["ic"] = { "Insert", "green" },
	["ix"] = { "Insert", "green" },
	["R"] = { "Replace", "lavender" },
	["Rc"] = { "Replace", "lavender" },
	["Rx"] = { "Replace", "lavender" },
	["Rv"] = { "V-Replace", "lavender" },
	["Rvc"] = { "V-Replace", "lavender" },
	["Rvx"] = { "V-Replace", "lavender" },
	["r"] = { "Replace", "lavender" },
	["rm"] = { "More", "flamingo" },
	["r?"] = { "Confirm", "red" },
	["c"] = { "Command", "red" },
	["cv"] = { "Ex-Mode", "red" },
	["ce"] = { "Ex-Mode", "red" },
	["!"] = { "Shell", "peach" },
	["t"] = { "Terminal", "peach" },
}

M.diagnostic_icons = {
	[vim.diagnostic.severity.ERROR] = "󰈸",
	[vim.diagnostic.severity.WARN] = "",
	[vim.diagnostic.severity.HINT] = "",
	[vim.diagnostic.severity.INFO] = "",
}

return M
